Repository Steve-xmh/amll-ttml-db, pull requests merged in 2025-06, with the labels that each got.

#4794 Add reviewer instruction.
  Reviewer Instruction.md
Labels: 词库议题

#4823 修复一个导致无法提交的关键bug
  scripts/utils.js
Labels: dependencies, 词库议题

#4832 修复自动规范化空格的逻辑
  scripts/utils.js
Labels: dependencies, 词库议题

#4837 修复一个日志 Bug
  scripts/run-submit-check.js
  scripts/ttml-parser.js
  scripts/utils.js
Labels: dependencies, 词库议题

#4925 [歌词提交] MARiA - Just Be Friends
  raw-lyrics/1751088007839-68000793-39f48301.ttml
Labels: 语种：日文

#4930 [歌词提交] 小豆沢こはね - Just Be Friends
  raw-lyrics/1751118701709-68000793-aa46d32e.ttml
Labels: 语种：日文
