Repository Steve-xmh/amll-ttml-db, pull requests merged in 2025-07, with the labels that each got.

#4975 Add files via upload
  instructions/image-20250702193615365.png
  instructions/image-20250702194644943.png
  instructions/image-20250702195344395.png
  instructions/image-20250702195545808.png
  instructions/image-20250702201505465.png
Labels: 词库议题

#4973 Rename instruction.md to instructions/instruction.md
  instructions/instruction.md
Labels: 词库议题

#5086 Update README.md
  README.md
Labels: dependencies

#5209 [歌词修正] 小豆沢こはね - Just Be Friends
  raw-lyrics/1753509076852-68000793-6c0bb879.ttml
Labels: 语种：日文

#5211 [歌词修正] MARiA - Just Be Friends
  raw-lyrics/1753509071182-68000793-55a81291.ttml
Labels: 语种：日文

#5217 [歌词提交] 白石杏 - Just Be Friends
  raw-lyrics/1753521362549-68000793-5d03e4e9.ttml
Labels: 语种：日文, プロセカ
